### ISSUE TITLE
FormatException: Unhandled Candidate format when calling `GenerativeModel.generateContent()`

### ISSUE THREAD

**Issue by devoncarew** [google/generative-ai-dart#80]
I don't know what the result from the server was, but here's the stack trace I saw:

```
Unhandled exception:
FormatException: Unhandled Candidate format
#0      _parseCandidate (package:google_generative_ai/src/api.dart:526:10)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#7      parseGenerateContentResponse (package:google_generative_ai/src/api.dart:470:41)
#8      GenerativeModel.generateContent (package:google_generative_ai/src/model.dart:127:14)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
We may have been trying to parse something similar to:

> {finishReason: SAFETY, index: 0, safetyRatings: [{category: HARM_CATEGORY_SEXUALLY_EXPLICIT, probability: NEGLIGIBLE}, {category: HARM_CATEGORY_HATE_SPEECH, probability: LOW}, {category: HARM_CATEGORY_HARASSMENT, probability: MEDIUM}, {category: HARM_CATEGORY_DANGEROUS_CONTENT, probability: NEGLIGIBLE}]}

**Comment by devoncarew** [comment]
Perhaps we're not handling parsing `"index": 0`? If so, we should be lenient about parsing fields we're not familiar with.
